### ISSUE TITLE
Msi GT75 - Compiling

### ISSUE THREAD

**Issue by smartgoblin** [marshevms/mlfc#23]
Hello,

I really would like to test it out. Unfortunately I don't have the expertise to install all the required dependencies to make it build.

Any option to have a build-ed version for Linux Mint?

**Comment by marshevms** [comment]
You just need to download from the release page https://github.com/marshevms/mlfc/releases/tag/0.5.0 and follow the deployment instructions.

**Comment by marshevms** [comment]
Ok, I forgot add dbus folder to archive. You can find it in the repo. Sorry.

**Comment by smartgoblin** [comment]
I did install QT with the run installer form their website but still get this message from the client:
`mlfc_client: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by mlfc_client)`

**Comment by marshevms** [comment]
You don't need to install Qt , just download already compiled 7z archive

**Comment by marshevms** [comment]
In root directory you have mlfc_cleint.sh

**Comment by smartgoblin** [comment]
Okay I got it working, nearly.
What I did:

1. execute server as root
2. execute client as root

Got the message:
`QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QSystemTrayIcon::setVisible: No Icon set
qml: An attempt to open the "/sys/kernel/debug/ec/ec0/io" file resulted in an error: No such file or directory
`

**Comment by marshevms** [comment]
Ok, it's cool. But now you need to see instruction from readme file. Deploying section. And nothing execute as root.
In repository you can find dbus folder. This file need to copy. And then, I see you have this error. You need to execute 
modprobe ec_sys write_support=1 as root from terminal.

**Comment by marshevms** [comment]
You can try install from deb https://mega.nz/file/Lt0GTbJD#4YmI7TCCp21PTEErAPeD9XxF6S6qzenOfbTB3Q4Ayo4

**Comment by smartgoblin** [comment]
Thanks for the Debian package.  All setup correctly now and working.
Clicking the cooler boost in the app and then disabling it keeps the fans at 4000rpm.
When I clicked the physical button on the laptop I could revert it to normal speeds or back to full speed, the app did pick up the changes.

**Comment by marshevms** [comment]
Ok. Thank you for your feedback. On my laptop, disabling the cooler boost causes the RPM to slow down slowly. What about advance profile? Can you make a video about bug with the cooler boost. And exec app from console, just write **mlfc_client**

**Comment by smartgoblin** [comment]
I first need to remove the old installs i did and retry the deb package as after reboot it is not working anymore.  Will test ASAP.

**Comment by smartgoblin** [comment]
Weird got again the following error:
charly@charly-GT75-Titan-8RG:~$ mlfc_client 
qml: An attempt to open the "/sys/kernel/debug/ec/ec0/io" file resulted in an error: No such file or directory

**Comment by smartgoblin** [comment]
Behavior on windows 10: https://1drv.ms/v/s!AiDzIKNovjHwvmRLRvwP72EErkMt?e=eTWLcW
Run from the terminal in Mint: https://1drv.ms/v/s!AiDzIKNovjHwvmPCBVDAwmyHGbgZ?e=z0SvWf

**Comment by smartgoblin** [comment]
Behavior on windows 10: https://1drv.ms/v/s!AiDzIKNovjHwvmRLRvwP72EErkMt?e=eTWLcW
Run from the terminal in Mint: https://1drv.ms/v/s!AiDzIKNovjHwvmPCBVDAwmyHGbgZ?e=5Qg8aR
