### ISSUE TITLE
Error: No such file or directory [Unknown Fan Mode 0D]

### ISSUE THREAD

**Issue by meanindra** [marshevms/mlfc#24]
![Screenshot from 2021-07-11 00-17-48](https://user-images.githubusercontent.com/36324543/125173605-c4c1f680-e1dd-11eb-847c-1a5b8a0e8f39.png)
Currently, I am using Pop!_OS 20.04 LTS

**Comment by marshevms** [comment]
Hi. You need to execute `sudo modprobe ec_sys write_support=1`

**Comment by marshevms** [comment]
DO you install from deb?

**Comment by meanindra** [comment]
yes

**Comment by marshevms** [comment]
ok, thanks. Did it help?

**Comment by meanindra** [comment]
![Screenshot from 2021-07-11 00-32-36](https://user-images.githubusercontent.com/36324543/125173914-8af1ef80-e1df-11eb-8cac-3e3fc73546e5.png)
now this error showing

**Comment by marshevms** [comment]
it's interesting

**Comment by meanindra** [comment]
![Screenshot from 2021-07-11 00-34-17](https://user-images.githubusercontent.com/36324543/125173963-cdb3c780-e1df-11eb-918c-d5628a046996.png)
and this

**Comment by marshevms** [comment]
Please reboot laptop. I think you change something manual.

**Comment by meanindra** [comment]
Reboot does not work
Same error

**Comment by marshevms** [comment]
What laptop model do you have?

**Comment by marshevms** [comment]
Can you upload file `/sys/kernel/debug/ec/ec0/io` ?

**Comment by Driglu4it** [comment]
I have similar problem.
This my /sys/kernel/debug/ec/ec0/io
[io.tar.gz](https://github.com/marshevms/mlfc/files/7033380/io.tar.gz)

**Comment by marshevms** [comment]
Thanks https://github.com/YoyPa/isw/issues/204#issuecomment-904012572

**Comment by marshevms** [comment]
If you install from deb you can try replace **mlfc_server** in _/usr/local/mlfc/bin_. Waiting for your feedback...
[mlfc_server.zip](https://github.com/marshevms/mlfc/files/7036755/mlfc_server.zip)

**Comment by Driglu4it** [comment]
> If you install from deb you can try replace **mlfc_server** in **_/usr/local/mlfc/bin_**. Waiting for your feedback...
> [mlfc_server.zip](https://github.com/marshevms/mlfc/files/7036755/mlfc_server.zip)

Thanks, now used without visible error, but give me more time to test all control modes. I will definitely write on the results.

**Comment by marshevms** [comment]
Ok, working only **auto** and **advanced**
