### ISSUE TITLE
Does this work in arch? On a ge72mvr?

### ISSUE THREAD

**Issue by ReikiJake** [marshevms/mlfc#28]
I am unfamiliar with doing builds but am definitely willing to learn but am unsure if the commands would be the same in arch or the locations. I am using garuda linux KDE Dragonized gaming edition latest version as of this post. I am absolutely loving the experience. Having setup a pure arch install on a different computer in the past I know how hard it can be to get everything working. With garuda it worked out of the box which was phenomenal and can play RE Villiage at 45 - 60 hz easy with no problems. I installed a few widgets to get my temps and other things on my desktop and notice my cpu running at around 70 degrees c at idle with not much going on and started looking into fan control and found isw and your gui. Tried and failed to build his python package lol not sure what happened. it just left me with a curser. I found yours after the fact and saw that you used some of his stuff but noticed you were in ubuntu and didn't recognize the locations at the end of your install guide. Anyhow he has listed support for my laptop and I have included the ec values as he had on his documentation. If you could let me know if it would work as is or could make it work that would be awesome. Maybe I am just too much of a newb but I would love some real fan control and appreciate any help or advice you have on the matter. No rush as my hardware button still works for cooler booster functionality I just have no way to adjust my fans At least I can see their temps now. Gaming on linux has been better for me than windows after this garuda install and am loving it. Thanks again for any help.

code on his site minus the brackets so github didn't mistake hash symbols for formating
>[179CEMS1]
[# GE72M_7RG
[# 179CEMS1.106
address_profile = MSI_ADDRESS_DEFAULT
fan_mode = 140
battery_charging_threshold = 100
[# CPU
cpu_temp_0 = 55
cpu_temp_1 = 61
cpu_temp_2 = 67
cpu_temp_3 = 73
cpu_temp_4 = 79
cpu_temp_5 = 85
cpu_fan_speed_0 = 40
cpu_fan_speed_1 = 48
cpu_fan_speed_2 = 56
cpu_fan_speed_3 = 66
cpu_fan_speed_4 = 76
cpu_fan_speed_5 = 86
cpu_fan_speed_6 = 95
[# GPU
gpu_temp_0 = 55
gpu_temp_1 = 60
gpu_temp_2 = 65
gpu_temp_3 = 70
gpu_temp_4 = 75
gpu_temp_5 = 75
gpu_fan_speed_0 = 0
gpu_fan_speed_1 = 54
gpu_fan_speed_2 = 62
gpu_fan_speed_3 = 70
gpu_fan_speed_4 = 78
gpu_fan_speed_5 = 86
gpu_fan_speed_6 = 86]

**Comment by ReikiJake** [comment]
Dang.
Term output-
>Packages (1) mlfc-0.5.1-1

Total Installed Size:  90.04 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                     [------------------------------------] 100%
(1/1) checking package integrity                                   [------------------------------------] 100%
(1/1) loading package files                                        [------------------------------------] 100%
(1/1) checking for file conflicts                                  [------------------------------------] 100%
(1/1) checking available disk space                                [------------------------------------] 100%
:: Running pre-transaction hooks...
(1/1) Performing snapper pre snapshots for the following configurations...
==> root: 21
:: Processing package changes...
(1/1) installing mlfc                                              [------------------------------------] 100%
warning: directory permissions differ on /etc/
filesystem: 755  package: 775
warning: directory permissions differ on /etc/dbus-1/
filesystem: 755  package: 775
warning: directory permissions differ on /etc/dbus-1/system.d/
filesystem: 755  package: 775
warning: directory permissions differ on /usr/
filesystem: 755  package: 775
warning: directory permissions differ on /usr/local/
filesystem: 755  package: 775
warning: directory permissions differ on /usr/local/bin/
filesystem: 755  package: 775
warning: directory permissions differ on /usr/local/share/
filesystem: 755  package: 775
warning: directory permissions differ on /usr/share/
filesystem: 755  package: 775
warning: directory permissions differ on /usr/share/applications/
filesystem: 755  package: 775
warning: directory permissions differ on /usr/share/dbus-1/
filesystem: 755  package: 775
warning: directory permissions differ on /usr/share/dbus-1/system-services/
filesystem: 755  package: 775
:: Running post-transaction hooks...
( 1/10) Arming ConditionNeedsUpdate...
( 2/10) Refreshing PackageKit...
( 3/10) Reloading system bus configuration...
( 4/10) Foreign/AUR package notification
mlfc 0.5.1-1
( 5/10) Orphaned package notification...
=> No orphans found.
( 6/10) Checking for .pacnew and .pacsave files...
.pac* files found:
/etc/retroarch.cfg.pacnew
Please check and merge
( 7/10) Updating pkgfile database...
( 8/10) Updating the desktop file MIME type cache...
( 9/10) Performing snapper post snapshots for the following configurations...
==> root: 22
(10/10) Syncing all file systems...


I ran the program anyways and got this error

An error occured
An attempt to open "/sys/kernel/debug/ec/io" file resulted in an error: No such file or directory

I am totally willing to experiment with you then you can claim it works on arch...
If time is more valuable I totally get it and thanks for trying. Going to clean up the files for now.
I wish I knew the config and system file structure better for arch or I might be of some help.
I have snapper so I can always restore my system back with a usb if we screw something up :-) Plus I only have a day into this system and dual boot with win backup if shtf.

**Comment by Shadowphoenix** [comment]
Uh normally i hate to wake up dead threads, but have you attempted the PKGBUILD for the AUR so far? i currently run ISW but... lets say its not the most convenient fancontrol out there, so i want to switch.

I am running Arch with Mainline Kernel and since i do not currently have any major alterations to basic premises of my system except for messing with my KDE-Theme, i figured i can help testing the package "as the most basic Arch there is" if needed.

**Comment by marshevms** [comment]
You can try https://github.com/marshevms/mlfc/issues/28#issuecomment-948814426 at first. I don't use arch, if you know how to create PKGBUILD for aur, you can try and if you have a problem i can help.

**Comment by Shadowphoenix** [comment]
will try it, to install it like that. Given the fact that there is a client and a Server i assume i can use Systemd to Daemonize applying my custom Fan-Curve by launching the server on boot, right?

**Comment by Shadowphoenix** [comment]
moving my stuff to a diffrent thread to not bloat this one unneccarily.
