### ISSUE TITLE
Don't show CPU RPM

### ISSUE THREAD

**Issue by don-boldyrev** [marshevms/mlfc#30]
Don't show CPU RPM. What does need for this?

**Comment by don-boldyrev** [comment]
![image](https://user-images.githubusercontent.com/27578057/167673426-f5a19679-3ddc-4da3-9e1d-c1e259830400.png)

**Comment by don-boldyrev** [comment]
Hello. Always 0 RPM. But i hear it. Model -  katana gf76

**Comment by marshevms** [comment]
Interesting.... It will be better if you can do something like this https://github.com/YoyPa/isw/issues/204#issuecomment-904012572

**Comment by don-boldyrev** [comment]
I don't understand almost everything in that message ( can you type detail instruction what I need to do?

**Comment by don-boldyrev** [comment]
What information do you need and when can I see it?

**Comment by marshevms** [comment]
Do you speak Russian?

**Comment by don-boldyrev** [comment]
Да, конечно

**Comment by marshevms** [comment]
Ты увидел, что там можно раскрыть сообщение? Там есть скриншоты двух программ. Было бы неплохо, если бы ты смог скачать эти программы и в одной открыть показания eс, а в dragon center менять режимы и скриншотить все это дело. Я еще заметил, что там нет покозаний температур,было бы хорошо,если ты смог бы их записать.
[RWEverything](http://rweverything.com/)
Это все нужно на виде делать :( Если ее нет нужно думать тогда....

**Comment by don-boldyrev** [comment]
![image](https://user-images.githubusercontent.com/27578057/167774926-8341689c-d28d-4196-ba18-2144380f0df2.png)
Низкая производительность - скорость авто. Температура процессора в среднем 47 градусов в покое кулеры не работают. температора графического процессора N/A

**Comment by don-boldyrev** [comment]
![image](https://user-images.githubusercontent.com/27578057/167775412-33d3a2bd-ef05-4df2-84ee-3ffea8321c4a.png)
Средняя производительность - скорость авто.  Низкая производительность - скорость авто. Температура процессора в среднем колеблется от 45 до 51 градуса в покое (ну то есть каких тяжелых программ не запущено) кулер процессора работает скорость где-то 2253 - 2307 RPM. температора графического процессора N/A.

**Comment by don-boldyrev** [comment]
![image](https://user-images.githubusercontent.com/27578057/167775984-2a7e7a47-b677-45df-9a87-e54042a9f3e9.png)
Высокая производительность - скорость авто. Температора процессора 38 градусов (также без тяжелых программ). Скорость вентилятора - 2264 - 2296 RPM. Видео карта - не задействована

**Comment by don-boldyrev** [comment]
![image](https://user-images.githubusercontent.com/27578057/167776737-a6a582ff-f4cb-4e4c-8493-09147506b69e.png)
Турбо - процессора 35 - 36 градусов при тех же условиях. Видео карта не задействована. Скорость вращения вентиляторов как и при высокой производительности

**Comment by don-boldyrev** [comment]
И еще вопрос не по теме, но если можно, то направь хотя бы где исать соотношение процентов работы кулера и температуры процессора на определенном (допустим моем компе). Дамп биоса нужен? - я там полный ноль, может к кому-то можно обратиться?

**Comment by marshevms** [comment]
Можешь еще включить cooler boost и скинуть скрин вместе со скоростью вращения вентиляторов?
Показания эти скорее всего дефолтные из прошивки, но ты можешь их сам выставить, как хочешь. Твой первый скрин, там есть график, вот скорее всего это твои дефолтные показатели

**Comment by don-boldyrev** [comment]
![image](https://user-images.githubusercontent.com/27578057/167791111-5fc5f186-1a46-4db6-8370-6f9d858b6c66.png)
![image](https://user-images.githubusercontent.com/27578057/167791223-090221e2-5c0e-4b6b-b5db-42700d2b7107.png)

**Comment by don-boldyrev** [comment]
> Можешь еще включить cooler boost и скинуть скрин вместе со скоростью вращения вентиляторов? Показания эти скорее всего дефолтные из прошивки, но ты можешь их сам выставить, как хочешь. Твой первый скрин, там есть график, вот скорее всего это твои дефолтные показатели

спасибо за ответ

**Comment by don-boldyrev** [comment]
Ещё заметил, что далеко не всегда на 55 градусах начинают работать кулеры, если начальную точку графика поставить на 0. По началу работает, потом пока до 70 условно не дойдёт, кулеры не начнут работать. Есть предположение с чем это может быть связано?

**Comment by marshevms** [comment]
Можешь показать график?

**Comment by marshevms** [comment]
Если ты включишь cooler boost, то тогда начнет отображаться скорость одного вентилятора?

**Comment by don-boldyrev** [comment]
> Если ты включишь cooler boost, то тогда начнет отображаться скорость одного вентилятора?

да

> Можешь показать график?

Такой же как в первом сообщении, только самая первая точка на значении не 38 процентов, а на нуле

**Comment by marshevms** [comment]
Попробуй передвинуть второе значение левее

**Comment by don-boldyrev** [comment]
поставил изначальное значение на 33 процента - не шумит, и греется в пределах, второе значение поставил на 45. Но обороты вентилятора так и не показываются.

**Comment by marshevms** [comment]
Я понял как это пофиксить, но у меня пока нет доступа к моему ноутбуку. Думаю через недели 2 будет фикс

**Comment by marshevms** [comment]
Спасибо за issue!

**Comment by don-boldyrev** [comment]
Спасибо, буду ждать

**Comment by marshevms** [comment]
[mlfc_server.zip](https://github.com/marshevms/mlfc/files/8750076/mlfc_server.zip)
Замени пожалуйста файл сервера

**Comment by don-boldyrev** [comment]
Правильно ли понимаю, что речь идет а файле в этой папке /usr/local/mlfc/bin? Если да, то решение не работает

**Comment by marshevms** [comment]
Покажи пожалуйста вывод комнды 
```cat /sys/devices/cpu/caps/pmu_name```

**Comment by don-boldyrev** [comment]
![image](https://user-images.githubusercontent.com/27578057/169770128-ef0a3760-32d9-4e2f-9027-f25b3f85739c.png)
icelake

**Comment by marshevms** [comment]
```cat /proc/cpuinfo```
Достаточно инфы по одному процессору

**Comment by marshevms** [comment]
[mlfc_server.zip](https://github.com/marshevms/mlfc/files/8756984/mlfc_server.zip)
Замени еще раз плиз

**Comment by don-boldyrev** [comment]
> [mlfc_server.zip](https://github.com/marshevms/mlfc/files/8756984/mlfc_server.zip) Замени еще раз плиз

Заменил также не работает, может по новой все переустановить?

**Comment by marshevms** [comment]
Установи тогда ```cpuid``` через ```apt install```
И покажи вывод ```cpuid -l 1 -1```

**Comment by don-boldyrev** [comment]
> Установи тогда `cpuid` через `apt install` И покажи вывод `cpuid -l 1 -1`

CPU:
   version information (1/eax):
      processor type  = primary processor (0)
      family          = 0x6 (6)
      model           = 0xd (13)
      stepping id     = 0x1 (1)
      extended family = 0x0 (0)
      extended model  = 0x8 (8)
      (family synth)  = 0x6 (6)
      (model synth)   = 0x8d (141)

   miscellaneous (1/ebx):
      process local APIC physical ID = 0xb (11)
      maximum IDs for CPUs in pkg    = 0x10 (16)
      CLFLUSH line size              = 0x8 (8)
      brand index                    = 0x0 (0)
   brand id = 0x00 (0): unknown
   feature information (1/edx):
      x87 FPU on chip                        = true
      VME: virtual-8086 mode enhancement     = true
      DE: debugging extensions               = true
      PSE: page size extensions              = true
      TSC: time stamp counter                = true
      RDMSR and WRMSR support                = true
      PAE: physical address extensions       = true
      MCE: machine check exception           = true
      CMPXCHG8B inst.                        = true
      APIC on chip                           = true
      SYSENTER and SYSEXIT                   = true
      MTRR: memory type range registers      = true
      PTE global bit                         = true
      MCA: machine check architecture        = true
      CMOV: conditional move/compare instr   = true
      PAT: page attribute table              = true
      PSE-36: page size extension            = true
      PSN: processor serial number           = false
      CLFLUSH instruction                    = true
      DS: debug store                        = true
      ACPI: thermal monitor and clock ctrl   = true
      MMX Technology                         = true
      FXSAVE/FXRSTOR                         = true
      SSE extensions                         = true
      SSE2 extensions                        = true
      SS: self snoop                         = true
      hyper-threading / multi-core supported = true
      TM: therm. monitor                     = true
      IA64                                   = false
      PBE: pending break event               = true
   feature information (1/ecx):
      PNI/SSE3: Prescott New Instructions     = true
      PCLMULDQ instruction                    = true
      DTES64: 64-bit debug store              = true
      MONITOR/MWAIT                           = true
      CPL-qualified debug store               = true
      VMX: virtual machine extensions         = true
      SMX: safer mode extensions              = false
      Enhanced Intel SpeedStep Technology     = true
      TM2: thermal monitor 2                  = true
      SSSE3 extensions                        = true
      context ID: adaptive or shared L1 data  = false
      SDBG: IA32_DEBUG_INTERFACE              = true
      FMA instruction                         = true
      CMPXCHG16B instruction                  = true
      xTPR disable                            = true
      PDCM: perfmon and debug                 = true
      PCID: process context identifiers       = true
      DCA: direct cache access                = false
      SSE4.1 extensions                       = true
      SSE4.2 extensions                       = true
      x2APIC: extended xAPIC support          = true
      MOVBE instruction                       = true
      POPCNT instruction                      = true
      time stamp counter deadline             = true
      AES instruction                         = true
      XSAVE/XSTOR states                      = true
      OS-enabled XSAVE/XSTOR                  = true
      AVX: advanced vector extensions         = true
      F16C half-precision convert instruction = true
      RDRAND instruction                      = true
      hypervisor guest status                 = false

**Comment by marshevms** [comment]
[mlfc_server.zip](https://github.com/marshevms/mlfc/files/8764860/mlfc_server.zip)
Думаю послдений)
Ну интел)) Два разных названия для 11 поколения)

**Comment by don-boldyrev** [comment]
ну что могу сказать - работает)) НО показывает почему-что это GPU а CPU, и наоборот. 
![image](https://user-images.githubusercontent.com/27578057/170184588-db1c1619-a070-42c8-882e-644824e12e2b.png)

**Comment by marshevms** [comment]
[mlfc_server.zip](https://github.com/marshevms/mlfc/files/8773206/mlfc_server.zip)
Проверь еще раз

**Comment by don-boldyrev** [comment]
Работает - огонь!!!! Спасибо большое)

**Comment by marshevms** [comment]
Большое тебе спасибо за issue!!! Отдельная благодарность, за то что не бросил на пол пути.
Вот ссылка на релиз https://github.com/marshevms/mlfc/releases/tag/0.5.2

Будут идеи или найдешь баги, обязательно пиши!!!
