### ISSUE TITLE
Installing on an MSI GS66 error

### ISSUE THREAD

**Issue by robouden** [marshevms/mlfc#33]
Hereby the screenshot of the error.

![Screenshot from 2022-05-28 23-11-18](https://user-images.githubusercontent.com/1387190/170829224-1ba40a35-7c3f-41d3-9fc1-537d6c3d9fd2.png)

Regards,
Rob Oudendijk

.

**Comment by marshevms** [comment]
Close the app and delete the file(/home/rob/.config/mlfc_client.toml). And reboot the laptop, if you have another program that changes your ec config, turn off it.

**Comment by robouden** [comment]
Removing the file got rid of the error and I could one time edit the graph. But when I saved the changes  and the errors showed up again. I tried to edit the file. But that did not work. I restored my backup from the day before and reinstalled. Now I can not edit the graph anymore. But no errors.

What to do?

Regards,
Rob Oudendijk

**Comment by marshevms** [comment]
You need to choose advanced profile.

**Comment by robouden** [comment]
Yes!!!!
