### ISSUE TITLE
How to autostart the client on Linux Mint

### ISSUE THREAD

**Issue by robouden** [marshevms/mlfc#34]
These days, when I start my computer, I start the client program automatically. I like to know how to add it automatically with no GUI, and I like to have the icon visual in my task bar. I tried to add the program to my startup programs, but that did not work.

Regards,
rob Oudendijk

**Comment by marshevms** [comment]
![image](https://user-images.githubusercontent.com/67420634/173192645-00380c35-7a0f-4b5e-9e81-7ef308c4884a.png)
Don't have the icon like this on task bar?

I did not quite understand. Do you start the program manually or you want the window not to be displayed at startup?

**Comment by robouden** [comment]
If I add the MSI Fan Control Program to my startup, the like the window to be closed.

**Comment by robouden** [comment]
Got it working the way I want by a Python scrip from https://www.youtube.com/watch?v=0cWkV-UOpXs
