### ISSUE TITLE
Archpackage - Error: please fill the config file: /home/neko/.config/mlfc_client/mlfc.toml 

### ISSUE THREAD

**Issue by Shadowphoenix** [marshevms/mlfc#35]
`

    current_mode = 'auto'
    icon_theme = 'light'

    [[mode]]
        [mode.auto]
        cpu_fan_speeds = []
        cpu_temps = []
        gpu_fan_speeds = []
        gpu_temps = []
        [[mode]]

    [[mode.advanced]]
        [mode.advanced.default]
        cpu_fan_speeds = []
        cpu_temps = []
        gpu_fan_speeds = []
        gpu_temps = []

`

opening this file revealed a bunch of empty arrays, i assume i am supposed to fill them with a basic grid relating Temps to Fanspeed - can you give me some examples what to put into this? also i think it WOULD make sense to put in some of these values from the getgo.

**Comment by marshevms** [comment]
For the first start program expects that your mode will be in auto. You can turn of all program that change fan speed and reboot your notebook. Or you can manual switch mode to auto.

```
current_mode = 'advanced'
icon_theme = 'light'

[[mode]]
    [mode.auto]
    cpu_fan_speeds = [ 47, 50, 56, 64, 72, 80, 80 ]
    cpu_temps = [ 55, 61, 67, 73, 79, 79 ]
    gpu_fan_speeds = [ 0, 53, 57, 61, 65, 69, 69 ]
    gpu_temps = [ 55, 60, 65, 70, 75, 75 ]

[[mode]]

    [[mode.advanced]]
        [mode.advanced.default]
        cpu_fan_speeds = [ 0, 47, 47, 55, 55, 62, 100 ]
        cpu_temps = [ 60, 65, 66, 75, 86, 90 ]
        gpu_fan_speeds = [ 0, 50, 57, 61, 65, 69, 69 ]
        gpu_temps = [ 55, 60, 65, 70, 75, 75 ]
```

**Comment by Shadowphoenix** [comment]
oh i see what i did wrong when trying to fill it myself then, i used semicolons instead of commas. Stupid Me.
